app:
  name: ui
  image:
    repository: 'onecx/onecx-permission-ui'
  routing:
    enabled: true
    path: /mfe/permission/
  
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      spec:
        exposedModule: "./OneCXPermissionModule"
        description: "OneCX Permission UI"
        note: "OneCX Permission UI module auto import via MF operator"
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          APP:
            EDIT: Edit app
            SAVE: Update and save app
            SEARCH: Search apps
            VIEW: View mode for app
          PERMISSION:
            GRANT: Assign or remove assignment of a permission to a role
            CREATE: Create permission
            DELETE: Delete permission
            EDIT: Edit permission
            SAVE: Update and save permission
          ROLE:
            CREATE: Create role
            DELETE: Delete role
            EDIT: Edit role
            SAVE: Update and save role
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "onecx-permission-ui"

# PIPE Config


